"""add facility fields km_end lat lon use_as_anchor

Revision ID: 28d00d81f482
Revises: e136487d39f8
Create Date: 2026-04-04 09:40:17.453406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d00d81f482'
down_revision: Union[str, Sequence[str], None] = 'e136487d39f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('km_end', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('use_as_anchor', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'use_as_anchor')
    op.drop_column('facilities', 'lon')
    op.drop_column('facilities', 'lat')
    op.drop_column('facilities', 'km_end')
    # ### end Alembic commands ###
